name: Linters

on: [pull_request]

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Commitsar check
        uses: aevea/commitsar@v0.11.0
      - name: Close Pull
        uses: peter-evans/close-pull@v1
        with:
          pull-request-number: 1
          comment: Auto-closing pull request
          delete-branch: false
