name: "build-test1"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          pattern: '\[(BUGFIX|DOCS|FEATURE|TASK)\] .+$'
          error: 'Your first line has to contain a commit type like "[BUGFIX]".'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
